---
title: "Readme"
output: html_document
date: '2022-05-17'
---
### Application
> This application will recommend some of the most popular songs to users depending on their preferences.

### Dataset

The data this week comes from BBC Music by way of Simon Jockers at Datawrapper.

The raw data can be found on https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-14/polls.csv.  
Album covers were retrived from Spotify, and you can access them via the Spotify API.

> Earlier this year, BBC Music asked more than 100 critics, artists, and other music industry folks from 15 countries for their five favorite hip-hop tracks. 
> Then they broke down the results of the poll into one definitive list. 
> But BBC Music didn’t just publish a best-of list, they also published the complete poll results and a description of the simple algorithm they ranked the songs with.  - Simon Jockers
                                                                                              
### Data Dictionary

#### polls.csv

> rank	(double) -->	Rank given by voters                 
> title 	(character) -->	Title of song                   
> artist	(character) -->	Artist                       
> gender	(character) -->	Gender of artist                    
> year	(double) -->	Year song released                    
> critic_name	(character) -->	Name of critic                 
> critic_rols	(character) -->	Critic's role                       
> critic_country	(character) -->	Critic's primary country                
> critic_country2	(character) -->	Critic's second country



